FROM mcr.microsoft.com/dotnet/runtime:8.0

ARG DOTNET_API_PATH_ARG=""
ARG DOTNET_API_CMD_ARG=""
ARG ASPNETCORE_ENVIRONMENT_ARG=""

ENV DOTNET_API_PATH=$DOTNET_API_PATH_ARG
ENV DOTNET_API_CMD=$DOTNET_API_CMD_ARG
ENV ASPNETCORE_ENVIRONMENT=$ASPNETCORE_ENVIRONMENT_ARG

ENV DOTNET_RUNNING_IN_CONTAINER=true
ENV ASPNETCORE_URLS=http://*:80
RUN mkdir /app
WORKDIR /app

COPY ./app/publish/$DOTNET_API_PATH .
RUN mv $DOTNET_API_CMD app

# Run migration then application
CMD ./app --db-update ; ./app
